/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MKE14F512xxx16
package_id: MKE14F512VLL16
mcu_data: ksdk2_0
processor_version: 4.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '1', peripheral: FLEXIO, signal: 'D, 3', pin_signal: PTE16/FTM2_CH7/FXIO_D3/TRGMUX_OUT7}
  - {pin_num: '2', peripheral: FLEXIO, signal: 'D, 2', pin_signal: PTE15/FTM2_CH6/FXIO_D2/TRGMUX_OUT6}
  - {pin_num: '3', peripheral: FLEXIO, signal: 'D, 1', pin_signal: ADC2_SE1/PTD1/FTM0_CH3/LPSPI1_SIN/FTM2_CH1/FXIO_D1/TRGMUX_OUT2}
  - {pin_num: '4', peripheral: FLEXIO, signal: 'D, 0', pin_signal: ADC2_SE0/PTD0/FTM0_CH2/LPSPI1_SCK/FTM2_CH0/FXIO_D0/TRGMUX_OUT1}
  - {pin_num: '5', peripheral: FLEXIO, signal: 'D, 5', pin_signal: ADC2_SE13/PTE11/PWT_IN1/LPTMR0_ALT1/FTM2_CH5/FXIO_D5/TRGMUX_OUT5}
  - {pin_num: '6', peripheral: FLEXIO, signal: 'D, 4', pin_signal: ADC2_SE12/PTE10/CLKOUT/FTM2_CH4/FXIO_D4/TRGMUX_OUT4}
  - {pin_num: '7', peripheral: GPIOE, signal: 'GPIO, 13', pin_signal: PTE13/FTM2_FLT0}
  - {pin_num: '8', peripheral: FTM2, signal: 'QD_PH, A', pin_signal: PTE5/TCLK2/FTM2_QD_PHA/FTM2_CH3/FXIO_D7/EWM_IN}
  - {pin_num: '9', peripheral: FTM2, signal: 'QD_PH, B', pin_signal: PTE4/BUSOUT/FTM2_QD_PHB/FTM2_CH2/FXIO_D6/EWM_OUT_b}
  - {pin_num: '10', peripheral: SUPPLY, signal: 'VDD, 0', pin_signal: VDD10}
  - {pin_num: '14', peripheral: SUPPLY, signal: 'VSS, 1', pin_signal: VSS15}
  - {pin_num: '15', peripheral: LPI2C0, signal: SCL, pin_signal: EXTAL/PTB7/LPI2C0_SCL}
  - {pin_num: '16', peripheral: LPI2C0, signal: SDA, pin_signal: XTAL/PTB6/LPI2C0_SDA}
  - {pin_num: '17', peripheral: CMP2, signal: 'IN, 3', pin_signal: ACMP2_IN3/PTE14/FTM0_FLT1/FTM2_FLT1}
  - {pin_num: '18', peripheral: CMP2, signal: OUT, pin_signal: PTE3/FTM0_FLT0/LPUART2_RTS/FTM2_FLT0/TRGMUX_IN6/ACMP2_OUT}
  - {pin_num: '19', peripheral: LPUART2, signal: TX, pin_signal: PTE12/FTM0_FLT3/LPUART2_TX}
  - {pin_num: '20', peripheral: LPUART2, signal: RX, pin_signal: PTD17/FTM0_FLT2/LPUART2_RX}
  - {pin_num: '21', peripheral: CMP2, signal: 'IN, 0', pin_signal: ACMP2_IN0/PTD16/FTM0_CH1}
  - {pin_num: '22', peripheral: CMP2, signal: 'IN, 1', pin_signal: ACMP2_IN1/PTD15/FTM0_CH0}
  - {pin_num: '23', peripheral: DAC0, signal: OUT, pin_signal: ACMP2_IN2/DAC0_OUT/PTE9/FTM0_CH7/LPUART2_CTS}
  - {pin_num: '24', peripheral: FTM2, signal: 'CH, 5', pin_signal: PTD14/FTM2_CH5/CLKOUT}
  - {pin_num: '25', peripheral: FTM2, signal: 'CH, 4', pin_signal: PTD13/FTM2_CH4/RTC_CLKOUT}
  - {pin_num: '26', peripheral: CMP0, signal: 'IN, 3', pin_signal: ACMP0_IN3/PTE8/FTM0_CH6}
  - {pin_num: '27', peripheral: CMP1, signal: OUT, pin_signal: PTB5/FTM0_CH5/LPSPI0_PCS1/TRGMUX_IN0/ACMP1_OUT}
  - {pin_num: '28', peripheral: CMP1, signal: 'IN, 2', pin_signal: ACMP1_IN2/PTB4/FTM0_CH4/LPSPI0_SOUT/TRGMUX_IN1}
  - {pin_num: '29', peripheral: CMP0, signal: 'IN, 4', pin_signal: ADC0_SE11/ACMP0_IN4/EXTAL32/PTC3/FTM0_CH3}
  - {pin_num: '30', peripheral: ADC0, signal: 'SE, 10', pin_signal: ADC0_SE10/ACMP0_IN5/XTAL32/PTC2/FTM0_CH2}
  - {pin_num: '31', peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/LPUART2_TX/FTM2_FLT3}
  - {pin_num: '32', peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: PTD6/LPUART2_RX/FTM2_FLT2}
  - {pin_num: '33', peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: PTD5/FTM2_CH3/LPTMR0_ALT2/FTM2_FLT1/PWT_IN2/TRGMUX_IN7}
  - {pin_num: '34', peripheral: LPUART2, signal: RTS, pin_signal: PTD12/FTM2_CH2/LPI2C1_HREQ/LPUART2_RTS}
  - {pin_num: '35', peripheral: LPUART2, signal: CTS, pin_signal: PTD11/FTM2_CH1/FTM2_QD_PHA/LPUART2_CTS}
  - {pin_num: '36', peripheral: GPIOD, signal: 'GPIO, 10', pin_signal: PTD10/FTM2_CH0/FTM2_QD_PHB}
  - {pin_num: '37', peripheral: SUPPLY, signal: 'VSS, 2', pin_signal: VSS38}
  - {pin_num: '39', peripheral: FTM1, signal: 'CH, 7', pin_signal: ADC0_SE9/ACMP1_IN3/PTC1/FTM0_CH1/FTM1_CH7}
  - {pin_num: '38', peripheral: SUPPLY, signal: 'VDD, 1', pin_signal: VDD39}
  - {pin_num: '40', peripheral: FTM1, signal: 'CH, 6', pin_signal: ADC0_SE8/ACMP1_IN4/PTC0/FTM0_CH0/FTM1_CH6}
  - {pin_num: '41', peripheral: LPI2C1, signal: SCL, pin_signal: ACMP1_IN5/PTD9/LPI2C1_SCL/FTM2_FLT3/FTM1_CH5}
  - {pin_num: '42', peripheral: LPI2C1, signal: SDA, pin_signal: PTD8/LPI2C1_SDA/FTM2_FLT2/FTM1_CH4}
  - {pin_num: '43', peripheral: ADC0, signal: 'SE, 15', pin_signal: ADC0_SE15/PTC17/FTM1_FLT3/LPI2C1_SCLS}
  - {pin_num: '44', peripheral: ADC0, signal: 'SE, 14', pin_signal: ADC0_SE14/PTC16/FTM1_FLT2/LPI2C1_SDAS}
  - {pin_num: '45', peripheral: FTM1, signal: 'CH, 3', pin_signal: ADC0_SE13/ACMP2_IN4/PTC15/FTM1_CH3}
  - {pin_num: '46', peripheral: FTM1, signal: 'CH, 2', pin_signal: ADC0_SE12/ACMP2_IN5/PTC14/FTM1_CH2}
  - {pin_num: '47', peripheral: FTM1, signal: 'QD_PH, A', pin_signal: ADC0_SE7/PTB3/FTM1_CH1/LPSPI0_SIN/FTM1_QD_PHA/TRGMUX_IN2}
  - {pin_num: '48', peripheral: FTM1, signal: 'QD_PH, B', pin_signal: ADC0_SE6/PTB2/FTM1_CH0/LPSPI0_SCK/FTM1_QD_PHB/TRGMUX_IN3}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: PTC13/FTM3_CH7/FTM2_CH7}
  - {pin_num: '50', peripheral: GPIOC, signal: 'GPIO, 12', pin_signal: PTC12/FTM3_CH6/FTM2_CH6}
  - {pin_num: '51', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: PTC11/FTM3_CH5}
  - {pin_num: '52', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: PTC10/FTM3_CH4}
  - {pin_num: '53', peripheral: GPIOB, signal: 'GPIO, 1', pin_signal: ADC0_SE5/ADC1_SE15/PTB1/LPUART0_TX/LPSPI0_SOUT/TCLK0}
  - {pin_num: '54', peripheral: LPSPI0, signal: PCS0, pin_signal: ADC0_SE4/ADC1_SE14/PTB0/LPUART0_RX/LPSPI0_PCS0/LPTMR0_ALT3/PWT_IN3}
  - {pin_num: '55', peripheral: LPUART1, signal: TX, pin_signal: ADC2_SE15/PTC9/LPUART1_TX/FTM1_FLT1/LPUART0_RTS}
  - {pin_num: '56', peripheral: LPUART1, signal: RX, pin_signal: ADC2_SE14/PTC8/LPUART1_RX/FTM1_FLT0/LPUART0_CTS}
  - {pin_num: '57', peripheral: LPUART1, signal: RTS, pin_signal: ADC0_SE3/ACMP1_IN1/PTA7/FTM0_FLT2/RTC_CLKIN/LPUART1_RTS}
  - {pin_num: '58', peripheral: LPUART1, signal: CTS, pin_signal: ADC0_SE2/ACMP1_IN0/PTA6/FTM0_FLT1/LPSPI1_PCS1/LPUART1_CTS}
  - {pin_num: '59', peripheral: FTM0, signal: 'CH, 7', pin_signal: ADC2_SE2/ACMP2_IN6/PTE7/FTM0_CH7/FTM3_FLT0}
  - {pin_num: '61', peripheral: SUPPLY, signal: 'VDD, 2', pin_signal: VDD62}
  - {pin_num: '60', peripheral: SUPPLY, signal: 'VSS, 3', pin_signal: VSS61}
  - {pin_num: '62', peripheral: FTM0, signal: 'CH, 6', pin_signal: PTA17/FTM0_CH6/FTM3_FLT0/EWM_OUT_b}
  - {pin_num: '63', peripheral: FTM0, signal: 'CH, 5', pin_signal: ADC2_SE3/PTB17/FTM0_CH5/LPSPI1_PCS3}
  - {pin_num: '64', peripheral: FTM0, signal: 'CH, 4', pin_signal: ADC1_SE15/PTB16/FTM0_CH4/LPSPI1_SOUT}
  - {pin_num: '65', peripheral: FTM0, signal: 'CH, 3', pin_signal: ADC1_SE14/PTB15/FTM0_CH3/LPSPI1_SIN}
  - {pin_num: '66', peripheral: FTM0, signal: 'CH, 2', pin_signal: ADC1_SE9/ADC2_SE9/PTB14/FTM0_CH2/LPSPI1_SCK}
  - {pin_num: '67', peripheral: FTM0, signal: 'CH, 1', pin_signal: ADC1_SE8/ADC2_SE8/PTB13/FTM0_CH1/FTM3_FLT1}
  - {pin_num: '68', peripheral: FTM0, signal: 'CH, 0', pin_signal: ADC1_SE7/PTB12/FTM0_CH0/FTM3_FLT2}
  - {pin_num: '69', peripheral: ADC1, signal: 'SE, 6', pin_signal: ADC1_SE6/ACMP1_IN6/PTD4/FTM0_FLT3/FTM3_FLT3}
  - {pin_num: '70', peripheral: ADC1, signal: 'SE, 3', pin_signal: ADC1_SE3/PTD3/FTM3_CH5/LPSPI1_PCS0/FXIO_D5/TRGMUX_IN4/NMI_b}
  - {pin_num: '71', peripheral: ADC1, signal: 'SE, 2', pin_signal: ADC1_SE2/PTD2/FTM3_CH4/LPSPI1_SOUT/FXIO_D4/TRGMUX_IN5}
  - {pin_num: '72', peripheral: LPUART0, signal: TX, pin_signal: ADC1_SE1/PTA3/FTM3_CH1/LPI2C0_SCL/EWM_IN/LPUART0_TX}
  - {pin_num: '73', peripheral: LPUART0, signal: RX, pin_signal: ADC1_SE0/PTA2/FTM3_CH0/LPI2C0_SDA/EWM_OUT_b/LPUART0_RX}
  - {pin_num: '74', peripheral: ADC2, signal: 'SE, 8', pin_signal: ADC2_SE8/PTB11/FTM3_CH3/LPI2C0_HREQ}
  - {pin_num: '75', peripheral: ADC2, signal: 'SE, 9', pin_signal: ADC2_SE9/PTB10/FTM3_CH2/LPI2C0_SDAS}
  - {pin_num: '76', peripheral: ADC2, signal: 'SE, 10', pin_signal: ADC2_SE10/PTB9/FTM3_CH1/LPI2C0_SCLS}
  - {pin_num: '77', peripheral: ADC2, signal: 'SE, 11', pin_signal: ADC2_SE11/PTB8/FTM3_CH0}
  - {pin_num: '78', peripheral: ADC0, signal: 'SE, 1', pin_signal: ADC0_SE1/ACMP0_IN1/PTA1/FTM1_CH1/LPI2C0_SDAS/FXIO_D3/FTM1_QD_PHA/LPUART0_RTS/TRGMUX_OUT0}
  - {pin_num: '80', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: ADC1_SE5/PTC7/LPUART1_TX/FTM3_CH3}
  - {pin_num: '79', peripheral: ADC0, signal: 'SE, 0', pin_signal: ADC0_SE0/ACMP0_IN0/PTA0/FTM2_CH1/LPI2C0_SCLS/FXIO_D2/FTM2_QD_PHA/LPUART0_CTS/TRGMUX_OUT3}
  - {pin_num: '81', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: ADC1_SE4/PTC6/LPUART1_RX/FTM3_CH2}
  - {pin_num: '82', peripheral: GPIOA, signal: 'GPIO, 16', pin_signal: ADC1_SE13/PTA16/FTM1_CH3/LPSPI1_PCS2}
  - {pin_num: '83', peripheral: LPSPI0, signal: PCS3, pin_signal: ADC1_SE12/PTA15/FTM1_CH2/LPSPI0_PCS3}
  - {pin_num: '84', peripheral: GPIOE, signal: 'GPIO, 6', pin_signal: ADC1_SE11/ACMP0_IN6/PTE6/LPSPI0_PCS2/FTM3_CH7/LPUART1_RTS}
  - {pin_num: '85', peripheral: LPSPI0, signal: SOUT, pin_signal: ADC1_SE10/PTE2/LPSPI0_SOUT/LPTMR0_ALT3/FTM3_CH6/PWT_IN3/LPUART1_CTS}
  - {pin_num: '87', peripheral: SUPPLY, signal: 'VDD, 3', pin_signal: VDD88}
  - {pin_num: '86', peripheral: SUPPLY, signal: 'VSS, 4', pin_signal: VSS87}
  - {pin_num: '88', peripheral: GPIOA, signal: 'GPIO, 14', pin_signal: PTA14/FTM0_FLT0/FTM3_FLT1/EWM_IN/FTM1_FLT0/BUSOUT}
  - {pin_num: '89', peripheral: GPIOA, signal: 'GPIO, 13', pin_signal: ADC2_SE4/PTA13/FTM1_CH7/LPI2C1_SCLS}
  - {pin_num: '90', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: ADC2_SE5/PTA12/FTM1_CH6/LPI2C1_SDAS}
  - {pin_num: '91', peripheral: GPIOA, signal: 'GPIO, 11', pin_signal: PTA11/FTM1_CH5/LPUART0_RX/FXIO_D1}
  - {pin_num: '92', peripheral: JTAG, signal: TDO, pin_signal: PTA10/FTM1_CH4/LPUART0_TX/FXIO_D0/JTAG_TDO/noetm_Trace_SWO}
  - {pin_num: '93', peripheral: LPSPI0, signal: SIN, pin_signal: ADC2_SE6/PTE1/LPSPI0_SIN/LPI2C0_HREQ/LPI2C1_SCL/FTM1_FLT1}
  - {pin_num: '94', peripheral: LPSPI0, signal: SCK, pin_signal: ADC2_SE7/PTE0/LPSPI0_SCK/TCLK1/LPI2C1_SDA/FTM1_FLT2}
  - {pin_num: '95', peripheral: JTAG, signal: TDI, pin_signal: PTC5/FTM2_CH0/RTC_CLKOUT/LPI2C1_HREQ/FTM2_QD_PHB/JTAG_TDI}
  - {pin_num: '96', peripheral: CoreDebug, signal: SWD_CLK, pin_signal: ACMP0_IN2/PTC4/FTM1_CH0/RTC_CLKOUT/EWM_IN/FTM1_QD_PHB/JTAG_TCLK/SWD_CLK}
  - {pin_num: '98', peripheral: CoreDebug, signal: SWD_DIO, pin_signal: PTA4/ACMP0_OUT/EWM_OUT_b/JTAG_TMS/SWD_DIO}
  - {pin_num: '99', peripheral: FLEXIO, signal: 'D, 7', pin_signal: PTA9/FXIO_D7/FTM3_FLT2/FTM1_FLT3}
  - {pin_num: '100', peripheral: FLEXIO, signal: 'D, 6', pin_signal: PTA8/FXIO_D6/FTM3_FLT3}
  - {pin_num: '12', peripheral: ADC0, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '12', peripheral: ADC1, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '12', peripheral: ADC2, signal: VREFH, pin_signal: VREFH}
  - {pin_num: '12', peripheral: DAC0, signal: REF_1, pin_signal: VREFH}
  - {pin_num: '11', peripheral: DAC0, signal: REF_2, pin_signal: VDDA}
  - {pin_num: '11', peripheral: SUPPLY, signal: 'VDDA, 0', pin_signal: VDDA}
  - {pin_num: '13', peripheral: ADC0, signal: VREFL, pin_signal: VREFL}
  - {pin_num: '97', peripheral: RCM, signal: RESET, pin_signal: PTA5/TCLK1/JTAG_TRST_b/RESET_b}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Clock Control: 0x01u */
    CLOCK_EnableClock(kCLOCK_PortE);

    /* PORTA0 (pin 79) is configured as ADC0_SE0 */
    PORT_SetPinMux(PORTA, 0U, kPORT_PinDisabledOrAnalog);

    /* PORTA1 (pin 78) is configured as ADC0_SE1 */
    PORT_SetPinMux(PORTA, 1U, kPORT_PinDisabledOrAnalog);

    /* PORTA10 (pin 92) is configured as JTAG_TDO */
    PORT_SetPinMux(PORTA, 10U, kPORT_MuxAlt7);

    /* PORTA11 (pin 91) is configured as PTA11 */
    PORT_SetPinMux(PORTA, 11U, kPORT_MuxAsGpio);

    /* PORTA12 (pin 90) is configured as PTA12 */
    PORT_SetPinMux(PORTA, 12U, kPORT_MuxAsGpio);

    /* PORTA13 (pin 89) is configured as PTA13 */
    PORT_SetPinMux(PORTA, 13U, kPORT_MuxAsGpio);

    /* PORTA14 (pin 88) is configured as PTA14 */
    PORT_SetPinMux(PORTA, 14U, kPORT_MuxAsGpio);

    /* PORTA15 (pin 83) is configured as LPSPI0_PCS3 */
    PORT_SetPinMux(PORTA, 15U, kPORT_MuxAlt3);

    /* PORTA16 (pin 82) is configured as PTA16 */
    PORT_SetPinMux(PORTA, 16U, kPORT_MuxAsGpio);

    /* PORTA17 (pin 62) is configured as FTM0_CH6 */
    PORT_SetPinMux(PORTA, 17U, kPORT_MuxAlt2);

    /* PORTA2 (pin 73) is configured as LPUART0_RX */
    PORT_SetPinMux(PORTA, 2U, kPORT_MuxAlt6);

    /* PORTA3 (pin 72) is configured as LPUART0_TX */
    PORT_SetPinMux(PORTA, 3U, kPORT_MuxAlt6);

    /* PORTA4 (pin 98) is configured as SWD_DIO */
    PORT_SetPinMux(PORTA, 4U, kPORT_MuxAlt7);

    /* PORTA5 (pin 97) is configured as RESET_b */
    PORT_SetPinMux(PORTA, 5U, kPORT_MuxAlt7);

    /* PORTA6 (pin 58) is configured as LPUART1_CTS */
    PORT_SetPinMux(PORTA, 6U, kPORT_MuxAlt6);

    /* PORTA7 (pin 57) is configured as LPUART1_RTS */
    PORT_SetPinMux(PORTA, 7U, kPORT_MuxAlt6);

    /* PORTA8 (pin 100) is configured as FXIO_D6 */
    PORT_SetPinMux(PORTA, 8U, kPORT_MuxAlt4);

    /* PORTA9 (pin 99) is configured as FXIO_D7 */
    PORT_SetPinMux(PORTA, 9U, kPORT_MuxAlt4);

    /* PORTB0 (pin 54) is configured as LPSPI0_PCS0 */
    PORT_SetPinMux(PORTB, 0U, kPORT_MuxAlt3);

    /* PORTB1 (pin 53) is configured as PTB1 */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAsGpio);

    /* PORTB10 (pin 75) is configured as ADC2_SE9 */
    PORT_SetPinMux(PORTB, 10U, kPORT_PinDisabledOrAnalog);

    /* PORTB11 (pin 74) is configured as ADC2_SE8 */
    PORT_SetPinMux(PORTB, 11U, kPORT_PinDisabledOrAnalog);

    /* PORTB12 (pin 68) is configured as FTM0_CH0 */
    PORT_SetPinMux(PORTB, 12U, kPORT_MuxAlt2);

    /* PORTB13 (pin 67) is configured as FTM0_CH1 */
    PORT_SetPinMux(PORTB, 13U, kPORT_MuxAlt2);

    /* PORTB14 (pin 66) is configured as FTM0_CH2 */
    PORT_SetPinMux(PORTB, 14U, kPORT_MuxAlt2);

    /* PORTB15 (pin 65) is configured as FTM0_CH3 */
    PORT_SetPinMux(PORTB, 15U, kPORT_MuxAlt2);

    /* PORTB16 (pin 64) is configured as FTM0_CH4 */
    PORT_SetPinMux(PORTB, 16U, kPORT_MuxAlt2);

    /* PORTB17 (pin 63) is configured as FTM0_CH5 */
    PORT_SetPinMux(PORTB, 17U, kPORT_MuxAlt2);

    /* PORTB2 (pin 48) is configured as FTM1_QD_PHB */
    PORT_SetPinMux(PORTB, 2U, kPORT_MuxAlt4);

    /* PORTB3 (pin 47) is configured as FTM1_QD_PHA */
    PORT_SetPinMux(PORTB, 3U, kPORT_MuxAlt4);

    /* PORTB4 (pin 28) is configured as ACMP1_IN2 */
    PORT_SetPinMux(PORTB, 4U, kPORT_PinDisabledOrAnalog);

    /* PORTB5 (pin 27) is configured as ACMP1_OUT */
    PORT_SetPinMux(PORTB, 5U, kPORT_MuxAlt7);

    /* PORTB6 (pin 16) is configured as LPI2C0_SDA */
    PORT_SetPinMux(PORTB, 6U, kPORT_MuxAlt2);

    /* PORTB7 (pin 15) is configured as LPI2C0_SCL */
    PORT_SetPinMux(PORTB, 7U, kPORT_MuxAlt2);

    /* PORTB8 (pin 77) is configured as ADC2_SE11 */
    PORT_SetPinMux(PORTB, 8U, kPORT_PinDisabledOrAnalog);

    /* PORTB9 (pin 76) is configured as ADC2_SE10 */
    PORT_SetPinMux(PORTB, 9U, kPORT_PinDisabledOrAnalog);

    /* PORTC0 (pin 40) is configured as FTM1_CH6 */
    PORT_SetPinMux(PORTC, 0U, kPORT_MuxAlt6);

    /* PORTC1 (pin 39) is configured as FTM1_CH7 */
    PORT_SetPinMux(PORTC, 1U, kPORT_MuxAlt6);

    /* PORTC10 (pin 52) is configured as PTC10 */
    PORT_SetPinMux(PORTC, 10U, kPORT_MuxAsGpio);

    /* PORTC11 (pin 51) is configured as PTC11 */
    PORT_SetPinMux(PORTC, 11U, kPORT_MuxAsGpio);

    /* PORTC12 (pin 50) is configured as PTC12 */
    PORT_SetPinMux(PORTC, 12U, kPORT_MuxAsGpio);

    /* PORTC13 (pin 49) is configured as PTC13 */
    PORT_SetPinMux(PORTC, 13U, kPORT_MuxAsGpio);

    /* PORTC14 (pin 46) is configured as FTM1_CH2 */
    PORT_SetPinMux(PORTC, 14U, kPORT_MuxAlt2);

    /* PORTC15 (pin 45) is configured as FTM1_CH3 */
    PORT_SetPinMux(PORTC, 15U, kPORT_MuxAlt2);

    /* PORTC16 (pin 44) is configured as ADC0_SE14 */
    PORT_SetPinMux(PORTC, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTC17 (pin 43) is configured as ADC0_SE15 */
    PORT_SetPinMux(PORTC, 17U, kPORT_PinDisabledOrAnalog);

    /* PORTC2 (pin 30) is configured as ADC0_SE10 */
    PORT_SetPinMux(PORTC, 2U, kPORT_PinDisabledOrAnalog);

    /* PORTC3 (pin 29) is configured as ACMP0_IN4 */
    PORT_SetPinMux(PORTC, 3U, kPORT_PinDisabledOrAnalog);

    /* PORTC4 (pin 96) is configured as SWD_CLK */
    PORT_SetPinMux(PORTC, 4U, kPORT_MuxAlt7);

    /* PORTC5 (pin 95) is configured as JTAG_TDI */
    PORT_SetPinMux(PORTC, 5U, kPORT_MuxAlt7);

    /* PORTC6 (pin 81) is configured as PTC6 */
    PORT_SetPinMux(PORTC, 6U, kPORT_MuxAsGpio);

    /* PORTC7 (pin 80) is configured as PTC7 */
    PORT_SetPinMux(PORTC, 7U, kPORT_MuxAsGpio);

    /* PORTC8 (pin 56) is configured as LPUART1_RX */
    PORT_SetPinMux(PORTC, 8U, kPORT_MuxAlt2);

    /* PORTC9 (pin 55) is configured as LPUART1_TX */
    PORT_SetPinMux(PORTC, 9U, kPORT_MuxAlt2);

    /* PORTD0 (pin 4) is configured as FXIO_D0 */
    PORT_SetPinMux(PORTD, 0U, kPORT_MuxAlt6);

    /* PORTD1 (pin 3) is configured as FXIO_D1 */
    PORT_SetPinMux(PORTD, 1U, kPORT_MuxAlt6);

    /* PORTD10 (pin 36) is configured as PTD10 */
    PORT_SetPinMux(PORTD, 10U, kPORT_MuxAsGpio);

    /* PORTD11 (pin 35) is configured as LPUART2_CTS */
    PORT_SetPinMux(PORTD, 11U, kPORT_MuxAlt6);

    /* PORTD12 (pin 34) is configured as LPUART2_RTS */
    PORT_SetPinMux(PORTD, 12U, kPORT_MuxAlt6);

    /* PORTD13 (pin 25) is configured as FTM2_CH4 */
    PORT_SetPinMux(PORTD, 13U, kPORT_MuxAlt2);

    /* PORTD14 (pin 24) is configured as FTM2_CH5 */
    PORT_SetPinMux(PORTD, 14U, kPORT_MuxAlt2);

    /* PORTD15 (pin 22) is configured as ACMP2_IN1 */
    PORT_SetPinMux(PORTD, 15U, kPORT_PinDisabledOrAnalog);

    /* PORTD16 (pin 21) is configured as ACMP2_IN0 */
    PORT_SetPinMux(PORTD, 16U, kPORT_PinDisabledOrAnalog);

    /* PORTD17 (pin 20) is configured as LPUART2_RX */
    PORT_SetPinMux(PORTD, 17U, kPORT_MuxAlt3);

    /* PORTD2 (pin 71) is configured as ADC1_SE2 */
    PORT_SetPinMux(PORTD, 2U, kPORT_PinDisabledOrAnalog);

    /* PORTD3 (pin 70) is configured as ADC1_SE3 */
    PORT_SetPinMux(PORTD, 3U, kPORT_PinDisabledOrAnalog);

    /* PORTD4 (pin 69) is configured as ADC1_SE6 */
    PORT_SetPinMux(PORTD, 4U, kPORT_PinDisabledOrAnalog);

    /* PORTD5 (pin 33) is configured as PTD5 */
    PORT_SetPinMux(PORTD, 5U, kPORT_MuxAsGpio);

    /* PORTD6 (pin 32) is configured as PTD6 */
    PORT_SetPinMux(PORTD, 6U, kPORT_MuxAsGpio);

    /* PORTD7 (pin 31) is configured as PTD7 */
    PORT_SetPinMux(PORTD, 7U, kPORT_MuxAsGpio);

    /* PORTD8 (pin 42) is configured as LPI2C1_SDA */
    PORT_SetPinMux(PORTD, 8U, kPORT_MuxAlt2);

    /* PORTD9 (pin 41) is configured as LPI2C1_SCL */
    PORT_SetPinMux(PORTD, 9U, kPORT_MuxAlt2);

    /* PORTE0 (pin 94) is configured as LPSPI0_SCK */
    PORT_SetPinMux(PORTE, 0U, kPORT_MuxAlt2);

    /* PORTE1 (pin 93) is configured as LPSPI0_SIN */
    PORT_SetPinMux(PORTE, 1U, kPORT_MuxAlt2);

    /* PORTE10 (pin 6) is configured as FXIO_D4 */
    PORT_SetPinMux(PORTE, 10U, kPORT_MuxAlt6);

    /* PORTE11 (pin 5) is configured as FXIO_D5 */
    PORT_SetPinMux(PORTE, 11U, kPORT_MuxAlt6);

    /* PORTE12 (pin 19) is configured as LPUART2_TX */
    PORT_SetPinMux(PORTE, 12U, kPORT_MuxAlt3);

    /* PORTE13 (pin 7) is configured as PTE13 */
    PORT_SetPinMux(PORTE, 13U, kPORT_MuxAsGpio);

    /* PORTE14 (pin 17) is configured as ACMP2_IN3 */
    PORT_SetPinMux(PORTE, 14U, kPORT_PinDisabledOrAnalog);

    /* PORTE15 (pin 2) is configured as FXIO_D2 */
    PORT_SetPinMux(PORTE, 15U, kPORT_MuxAlt6);

    /* PORTE16 (pin 1) is configured as FXIO_D3 */
    PORT_SetPinMux(PORTE, 16U, kPORT_MuxAlt6);

    /* PORTE2 (pin 85) is configured as LPSPI0_SOUT */
    PORT_SetPinMux(PORTE, 2U, kPORT_MuxAlt2);

    /* PORTE3 (pin 18) is configured as ACMP2_OUT */
    PORT_SetPinMux(PORTE, 3U, kPORT_MuxAlt7);

    /* PORTE4 (pin 9) is configured as FTM2_QD_PHB */
    PORT_SetPinMux(PORTE, 4U, kPORT_MuxAlt3);

    /* PORTE5 (pin 8) is configured as FTM2_QD_PHA */
    PORT_SetPinMux(PORTE, 5U, kPORT_MuxAlt3);

    /* PORTE6 (pin 84) is configured as PTE6 */
    PORT_SetPinMux(PORTE, 6U, kPORT_MuxAsGpio);

    /* PORTE7 (pin 59) is configured as FTM0_CH7 */
    PORT_SetPinMux(PORTE, 7U, kPORT_MuxAlt2);

    /* PORTE8 (pin 26) is configured as ACMP0_IN3 */
    PORT_SetPinMux(PORTE, 8U, kPORT_PinDisabledOrAnalog);

    /* PORTE9 (pin 23) is configured as DAC0_OUT */
    PORT_SetPinMux(PORTE, 9U, kPORT_PinDisabledOrAnalog);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
